apiVersion: v1
kind: Service
metadata:
  name: external-ip-diskstation
  namespace: networking
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip-diskstation
  namespace: networking
subsets:
- addresses:
  - ip: 192.168.0.3
  ports:
  - name: http
    port: 5000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: external-ip-diskstation
spec:
  rules:
  - host: ds.${SECRET_DOMAIN}
    http:
      paths:
      - backend:
          serviceName: external-ip-diskstation
          servicePort: 80
        path: /
  tls:
    - hosts:
      - ds.${SECRET_DOMAIN}