---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: flux-system
spec:
  interval: 60m
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
  timeout: 2m
