apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: minecraft-1
    namespace: minecraft
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
            chart: minecraft
            version: 3.1.6
            sourceRef:
                kind: HelmRepository
                name: itzg-charts
                namespace: flux-system
    values:
        image: itzg/minecraft-server
        imageTag: 2021.9.0-multiarch-latest
        persistence:
          storageClass: "nfs-client"
          dataDir:
            enabled: true
            Size: 10Gi
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 2048Mi
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 10
          successThreshold: 1
          timeoutSeconds: 1
        startupProbe:
          enabled: true
          failureThreshold: 30
          periodSeconds: 10
        podAnnotations:
          backup.velero.io/backup-volumes: datadir
        extraEnv:
          ENABLE_AUTOPAUSE: TRUE
        minecraftServer:
          eula: "TRUE"
          version: "LATEST"
          type: VANILLA              
          jvmOpts: "-Xms512m -Xmx1516m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
          memory: 1516M
          difficulty: normal
          maxTickTime: -1
          serviceType: LoadBalancer
          gameMode: creative
          motd: "Caro + Sofia"
          icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-13.png
          loadBalancerIP: ${MINECRAFT_1_LB}
          rcon:
            enabled: false
            port: 25575
            password: "mc-rcon"
            serviceType: LoadBalancer
          extraPorts:
            - name: map
              containerPort: 8123
              service:
                enabled: true
                type: ClusterIP
                port: 8123
              ingress:
                enabled: true
                annotations:
                  kubernetes.io/ingress.class: nginx
                  nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"
                hosts:
                  - name: mc-map.${SECRET_DOMAIN}
                    path: /
                tls:
                - hosts:
                  - mc-map.${SECRET_DOMAIN}