---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.0.240-192.168.0.249
  INGRESS_NGINX_LB: 192.168.0.240

  HASS_LB_IP: 192.168.0.241
  MOSQUITTO_LB_IP: 192.168.0.242
