---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vadimkim.github.io/cert-manager-webhook-hetzner
      chart: cert-manager-webhook-hetzner
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: flux-system
